[mongo]
connection_url = "mongodb://localhost:27017"
database_name = "restaurant_conductor"
recipe_collection = "recipe"

[kafka]
host = "localhost:29092"
consumer_group = "restaurant_conductor"
recipe_generated_topic = "recipe_generated"
order_prepared_topic = "order_prepared"
order_created_topic = "order_created"
